spring:
  application:
    name: "Ngelmak Project - Core"
  cloud:
    vault:
      uri: http://vault:8200 # vault docker service name and port
      authentication: approle
      fail-fast: true # Enable fail-fast to force confirmation. Spring Boot to crash immediately when Vault/OpenBao is not reachable
      app-role:
        role-id: ${VAULT_ROLE_ID} # The Vault AppRole Role ID
        secret-id: ${VAULT_SECRET_ID} # The Vault AppRole Secret ID
      database:
        enabled: true # Disable the database backend if not needed. Set to true if you want to use Vault's database secrets engine for dynamic credentials.
        backend: database
        role: ngelmak-springboot-role # The Vault role that has permissions to access the database credentials
      kv:
        enabled: true

  datasource:
    hikari:
      initialization-fail-timeout: 0
    url: jdbc:postgresql://postgres:5432/ngelmakdb

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none # Use application-bootstrap.yml for updating the database schema
  servlet:
    multipart:
      enabled: true
      max-file-size: 30MB
      max-request-size: 30MB
      resolve-lazily: false

  resources:
    cache-period: 86400

logging:
  level:
    org.springframework.vault: DEBUG
    org.springframework.boot.autoconfigure: INFO

debug: false