spring:
  application:
    name: "Ngelmak Project - Core"
  config:
    import: vault:// # Enable Vault as a Config Data source
  cloud:
    vault:
      uri: http://vault:8200
      authentication: approle
      config:
        lifecycle:
          enabled: true # Enable lease renewal (default)
          min-renewal: 3600 # Minimum time between renewals (1 hour)
          expiry-threshold: 7200 # Renew this long before expiration (2 hours)
      fail-fast: true # Enable fail-fast to force confirmation. Spring Boot to crash immediately when Vault/OpenBao is not reachable
      app-role:
        role-id: ${VAULT_ROLE_ID}
        secret-id: ${VAULT_SECRET_ID}
      database:
        enabled: true
        backend: database
        role: ngelmak-springboot-role # The Vault role that has permissions to access the database credentials
      kv:
        enabled: true
        backend: secret
        application-name: jjwt
        default-context: "" # or omit this entirely
  datasource:
    hikari.initialization-fail-timeout: 0 # Fail immediately if pool can't initialize
    hikari.max-lifetime: 600000 # Max connection lifetime before closing (10 min)
    hikari.idle-timeout: 300000 # Close idle connections after 5 minutes
    hikari.connection-test-query: SELECT 1 # Validation query to test connections
    hikari.validation-timeout: 5000 # Timeout for validation query (5 seconds)
    hikari.minimum-idle: 5 # Minimum idle connections to maintain
    hikari.maximum-pool-size: 20 # Maximum connections in pool
    url: jdbc:postgresql://postgres:5432/ngelmakdb
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none # Use application-bootstrap.yml for updating the database schema
  jackson:
    serialization:
      fail-on-empty-beans: false
  data:
    redis:
      client-type: lettuce
      host: redis
      port: 6379
      timeout: 60000ms
      jedis:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: -1ms
  servlet:
    multipart:
      enabled: true
      max-file-size: 30MB
      max-request-size: 30MB
      resolve-lazily: false
  resources:
    cache-period: 86400

server:
  port: 37373
# Will be set by vault
jwt-secret-key:

# SeaweedFS configuration
seaweedfs:
  filer:
    url: http://filer:9555
file:
  public:
    base-url: https://storage.ngelmak.org

debug: false
logging:
  level:
    root: INFO
    "[org.springframework.vault]": DEBUG

# set refresh interval for static secrets
